import { describe, expect, it } from 'vitest';

describe('@jackpotkit/core public entrypoint', () => {
  it('initializes safely in Node and exposes the intentional Phase 5 runtime API', async () => {
    const core = await import('./index.js');

    expect(Object.keys(core).sort()).toEqual(
      [
        'AnimationError',
        'DEFAULT_BINGO_MAX_NUMBER',
        'DEFAULT_BINGO_MIN_NUMBER',
        'DEFAULT_BINGO_PATTERNS',
        'DEFAULT_BINGO_SIZE',
        'GAME_EVENT_TYPES',
        'GAME_STATUSES',
        'GameStateError',
        'InvalidConfigurationError',
        'InvalidResultError',
        'InvalidSegmentError',
        'JackpotKitError',
        'MathRandomSource',
        'ResultProviderError',
        'SeededRandomSource',
        'assertRandomValue',
        'assertValidBingoBoard',
        'assertValidBingoConfiguration',
        'assertValidBingoNumber',
        'assertValidConfiguration',
        'assertValidResult',
        'assertValidScratchCardConfiguration',
        'assertValidScratchCardSelection',
        'assertValidScratchPoint',
        'assertValidScratchProgress',
        'assertValidSlotMachineConfiguration',
        'assertValidSlotMachineSelection',
        'assertValidSlotSymbols',
        'assertValidSpinWheelSegments',
        'assertValidSpinWheelSelection',
        'calculateSpinWheelDestination',
        'createBingo',
        'createBingoBoard',
        'createBingoPatternDefinitions',
        'createDefaultSlotPaylines',
        'createRandomSlotSelection',
        'createSpinWheel',
        'createGameEvent',
        'createScratchCard',
        'createScratchProgressTracker',
        'createSlotMachine',
        'createValidationResult',
        'evaluateBingoPatterns',
        'evaluateSlotPaylines',
        'isGameStatus',
        'isRandomValue',
        'nextRandomValue',
        'resolveResult',
        'selectSlotSymbol',
        'selectSpinWheelSegment',
        'validateScratchCardConfiguration',
        'validateSlotMachineConfiguration',
        'validateSlotSymbols',
        'validateSpinWheelSegments',
        'validateSpinWheelSelection',
      ].sort(),
    );
  });
});
